server:
  port: 8083

# redis host and port parameters
redis:
  host: localhost
  port: 6379

# streamKeys to be used by producers
stream:
  key: "mystream"

# groupIds to be used by consumers
groups:
  product: "productcreated"