name: 'Build Project'
description: 'Build project with gradle'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Gradle build
      run: ./gradlew build
      shell: bash