name: Build

on:
  push: {}
  workflow_call: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3

      - name: Build Project
        uses: ./.github/actions/build-project